<?php

namespace Proxies\__CG__\furies\orbitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customers extends \furies\orbitBundle\Entity\Customers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'crnNo', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'title', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'name', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'doorno', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address1', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address2', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'city', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'pin', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'custType', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'mobile', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'email', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'custCategory', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'doe', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'live', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'comment', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'createdby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'modifiedby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'insertdate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'modifieddate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'customersId');
        }

        return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'crnNo', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'title', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'name', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'doorno', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address1', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'address2', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'city', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'pin', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'custType', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'mobile', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'email', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'custCategory', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'doe', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'live', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'comment', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'createdby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'modifiedby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'insertdate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'modifieddate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Customers' . "\0" . 'customersId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCrnNo($crnNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrnNo', array($crnNo));

        return parent::setCrnNo($crnNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrnNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrnNo', array());

        return parent::getCrnNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoorno($doorno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoorno', array($doorno));

        return parent::setDoorno($doorno);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoorno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoorno', array());

        return parent::getDoorno();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress1($address1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress1', array($address1));

        return parent::setAddress1($address1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress1', array());

        return parent::getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', array($address2));

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', array());

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPin($pin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPin', array($pin));

        return parent::setPin($pin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPin', array());

        return parent::getPin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustType($custType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustType', array($custType));

        return parent::setCustType($custType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustType', array());

        return parent::getCustType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustCategory($custCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustCategory', array($custCategory));

        return parent::setCustCategory($custCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustCategory', array());

        return parent::getCustCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoe($doe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoe', array($doe));

        return parent::setDoe($doe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoe', array());

        return parent::getDoe();
    }

    /**
     * {@inheritDoc}
     */
    public function setLive($live)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLive', array($live));

        return parent::setLive($live);
    }

    /**
     * {@inheritDoc}
     */
    public function getLive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLive', array());

        return parent::getLive();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', array($comment));

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', array());

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedby($createdby)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedby', array($createdby));

        return parent::setCreatedby($createdby);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedby', array());

        return parent::getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedby($modifiedby)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedby', array($modifiedby));

        return parent::setModifiedby($modifiedby);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedby', array());

        return parent::getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsertdate($insertdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsertdate', array($insertdate));

        return parent::setInsertdate($insertdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsertdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsertdate', array());

        return parent::getInsertdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifieddate($modifieddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifieddate', array($modifieddate));

        return parent::setModifieddate($modifieddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifieddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifieddate', array());

        return parent::getModifieddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomersId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCustomersId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomersId', array());

        return parent::getCustomersId();
    }

}
