<?php

namespace Proxies\__CG__\furies\orbitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PrepaidTariff extends \furies\orbitBundle\Entity\PrepaidTariff implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffName', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffValiditydays', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffUsagelimit', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffDownloadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffCapdownloadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffUploadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffCapuploadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffActive', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffBillafterlimit', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffAmountpermb', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffAmount', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'idprepaidTariff');
        }

        return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffName', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffValiditydays', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffUsagelimit', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffDownloadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffCapdownloadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffUploadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffCapuploadspeed', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffActive', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffBillafterlimit', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffAmountpermb', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'prepaidTariffAmount', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\PrepaidTariff' . "\0" . 'idprepaidTariff');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PrepaidTariff $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffName($prepaidTariffName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffName', array($prepaidTariffName));

        return parent::setPrepaidTariffName($prepaidTariffName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffName', array());

        return parent::getPrepaidTariffName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffValiditydays($prepaidTariffValiditydays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffValiditydays', array($prepaidTariffValiditydays));

        return parent::setPrepaidTariffValiditydays($prepaidTariffValiditydays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffValiditydays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffValiditydays', array());

        return parent::getPrepaidTariffValiditydays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffUsagelimit($prepaidTariffUsagelimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffUsagelimit', array($prepaidTariffUsagelimit));

        return parent::setPrepaidTariffUsagelimit($prepaidTariffUsagelimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffUsagelimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffUsagelimit', array());

        return parent::getPrepaidTariffUsagelimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffDownloadspeed($prepaidTariffDownloadspeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffDownloadspeed', array($prepaidTariffDownloadspeed));

        return parent::setPrepaidTariffDownloadspeed($prepaidTariffDownloadspeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffDownloadspeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffDownloadspeed', array());

        return parent::getPrepaidTariffDownloadspeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffCapdownloadspeed($prepaidTariffCapdownloadspeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffCapdownloadspeed', array($prepaidTariffCapdownloadspeed));

        return parent::setPrepaidTariffCapdownloadspeed($prepaidTariffCapdownloadspeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffCapdownloadspeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffCapdownloadspeed', array());

        return parent::getPrepaidTariffCapdownloadspeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffUploadspeed($prepaidTariffUploadspeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffUploadspeed', array($prepaidTariffUploadspeed));

        return parent::setPrepaidTariffUploadspeed($prepaidTariffUploadspeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffUploadspeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffUploadspeed', array());

        return parent::getPrepaidTariffUploadspeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffCapuploadspeed($prepaidTariffCapuploadspeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffCapuploadspeed', array($prepaidTariffCapuploadspeed));

        return parent::setPrepaidTariffCapuploadspeed($prepaidTariffCapuploadspeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffCapuploadspeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffCapuploadspeed', array());

        return parent::getPrepaidTariffCapuploadspeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffActive($prepaidTariffActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffActive', array($prepaidTariffActive));

        return parent::setPrepaidTariffActive($prepaidTariffActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffActive', array());

        return parent::getPrepaidTariffActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffBillafterlimit($prepaidTariffBillafterlimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffBillafterlimit', array($prepaidTariffBillafterlimit));

        return parent::setPrepaidTariffBillafterlimit($prepaidTariffBillafterlimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffBillafterlimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffBillafterlimit', array());

        return parent::getPrepaidTariffBillafterlimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffAmountpermb($prepaidTariffAmountpermb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffAmountpermb', array($prepaidTariffAmountpermb));

        return parent::setPrepaidTariffAmountpermb($prepaidTariffAmountpermb);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffAmountpermb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffAmountpermb', array());

        return parent::getPrepaidTariffAmountpermb();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrepaidTariffAmount($prepaidTariffAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrepaidTariffAmount', array($prepaidTariffAmount));

        return parent::setPrepaidTariffAmount($prepaidTariffAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrepaidTariffAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrepaidTariffAmount', array());

        return parent::getPrepaidTariffAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdprepaidTariff()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdprepaidTariff();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprepaidTariff', array());

        return parent::getIdprepaidTariff();
    }

}
