<?php

namespace Proxies\__CG__\furies\orbitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Radgroupreply extends \furies\orbitBundle\Entity\Radgroupreply implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'groupname', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'attribute', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'op', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'value', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'groupname', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'attribute', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'op', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'value', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Radgroupreply' . "\0" . 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Radgroupreply $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setGroupname($groupname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupname', array($groupname));

        return parent::setGroupname($groupname);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupname', array());

        return parent::getGroupname();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', array($attribute));

        return parent::setAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', array());

        return parent::getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setOp($op)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOp', array($op));

        return parent::setOp($op);
    }

    /**
     * {@inheritDoc}
     */
    public function getOp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOp', array());

        return parent::getOp();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', array($value));

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', array());

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
