<?php

namespace Proxies\__CG__\furies\orbitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prepaidcircuits extends \furies\orbitBundle\Entity\Prepaidcircuits implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactperson', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactmobile', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactemail', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'startdate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'noofstaticips', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'staticipaddress', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'createdby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'createddate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'modifiedby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'modifieddatetime', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'circuitid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'routerid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'customerid');
        }

        return array('__isInitialized__', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactperson', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactmobile', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'contactemail', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'startdate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'noofstaticips', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'staticipaddress', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'createdby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'createddate', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'modifiedby', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'modifieddatetime', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'companyid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'circuitid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'routerid', '' . "\0" . 'furies\\orbitBundle\\Entity\\Prepaidcircuits' . "\0" . 'customerid');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prepaidcircuits $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setContactperson($contactperson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactperson', array($contactperson));

        return parent::setContactperson($contactperson);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactperson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactperson', array());

        return parent::getContactperson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactmobile($contactmobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactmobile', array($contactmobile));

        return parent::setContactmobile($contactmobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactmobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactmobile', array());

        return parent::getContactmobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactemail($contactemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactemail', array($contactemail));

        return parent::setContactemail($contactemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactemail', array());

        return parent::getContactemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartdate($startdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartdate', array($startdate));

        return parent::setStartdate($startdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartdate', array());

        return parent::getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoofstaticips($noofstaticips)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoofstaticips', array($noofstaticips));

        return parent::setNoofstaticips($noofstaticips);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoofstaticips()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoofstaticips', array());

        return parent::getNoofstaticips();
    }

    /**
     * {@inheritDoc}
     */
    public function setStaticipaddress($staticipaddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStaticipaddress', array($staticipaddress));

        return parent::setStaticipaddress($staticipaddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getStaticipaddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStaticipaddress', array());

        return parent::getStaticipaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedby($createdby)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedby', array($createdby));

        return parent::setCreatedby($createdby);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedby', array());

        return parent::getCreatedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateddate($createddate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateddate', array($createddate));

        return parent::setCreateddate($createddate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateddate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateddate', array());

        return parent::getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifiedby($modifiedby)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifiedby', array($modifiedby));

        return parent::setModifiedby($modifiedby);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedby()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedby', array());

        return parent::getModifiedby();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifieddatetime($modifieddatetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifieddatetime', array($modifieddatetime));

        return parent::setModifieddatetime($modifieddatetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifieddatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifieddatetime', array());

        return parent::getModifieddatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyid($companyid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyid', array($companyid));

        return parent::setCompanyid($companyid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyid', array());

        return parent::getCompanyid();
    }

    /**
     * {@inheritDoc}
     */
    public function getCircuitid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCircuitid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCircuitid', array());

        return parent::getCircuitid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRouterid(\furies\orbitBundle\Entity\Supportedrouters $routerid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRouterid', array($routerid));

        return parent::setRouterid($routerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getRouterid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRouterid', array());

        return parent::getRouterid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerid(\furies\orbitBundle\Entity\Customers $customerid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerid', array($customerid));

        return parent::setCustomerid($customerid);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerid', array());

        return parent::getCustomerid();
    }

}
